migrate_up:
	migrate -path db/migration -database "$(DB_URL)" -verbose up

migrate_down:
	migrate -path db/migration -database "$(DB_URL)" -verbose down

sqlc:
	sqlc generate

simple_test:
	go test ./...

test:
	go test -v ./...

test_coverage:
	go test -coverpkg=./... ./...

.PHONY: migrate_up migrate_down sqlc simple_test test test_coverage
